#!/bin/bash

if [[ $# -eq 0 ]] ; then
    echo "Usage: $(basename $BASH_SOURCE) [fileprefix ...]"
    exit 1
fi

for prefix in "$@"; do
    if [[ -e $prefix.html ]]; then
        echo "$prefix.html already exists!"
        exit 2
    fi
done

for prefix in "$@"; do
    cat >$prefix.html <<EOF
<html>

<head>
  <title>$prefix</title>

  <!-- UNCOMMENT FOR INCLUDING CUSTOM CSS
  <link href="css/site.css" rel="stylesheet"></link>
  -->
</head>

<body>

</body>

</html>
EOF
done

